const GET_USER_INFO_BY_HASH = "GET_USER_INFO_BY_HASH"
const GET_USER_INFO_BY_ID = "GET_USER_INFO_BY_ID"
const GET_USER_ROLE = "GET_USER_ROLE"
const AUTH_USER_BY_EMAIL_PASSWORD = "AUTH_USER_BY_EMAIL_PASSWORD"

const UserActions = {
    GET_USER_INFO_BY_HASH,
    GET_USER_INFO_BY_ID,
    GET_USER_ROLE,
    AUTH_USER_BY_EMAIL_PASSWORD,
};

export default UserActions;